In [26]:
import pandas as pd 
import numpy as np

In [36]:
df = pd.read_csv('spam.csv',encoding='windows-1252')
df.head()

v1                                                 v2   v3   v4   v5
0   ham  Go until jurong point, crazy.. Available only ...  NaN  NaN  NaN
1   ham                      Ok lar... Joking wif u oni...  NaN  NaN  NaN
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...  NaN  NaN  NaN
3   ham  U dun say so early hor... U c already then say...  NaN  NaN  NaN
4   ham  Nah I don't think he goes to usf, he lives aro...  NaN  NaN  NaN

In [37]:
df.v1.value_counts()


v1
ham     4825
spam     747
Name: count, dtype: int64

In [38]:
df['spam'] = df['v1'].apply(lambda x: 1 if x == 'spam' else 0)


In [39]:
df.rename(columns={'v1': 'Category', 'v2': 'Message'}, inplace=True)

In [40]:
df.drop(columns=['v3', 'v4', 'v5'], inplace=True)

In [41]:
df.head(20)

Category                                            Message  spam
0       ham  Go until jurong point, crazy.. Available only ...     0
1       ham                      Ok lar... Joking wif u oni...     0
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3       ham  U dun say so early hor... U c already then say...     0
4       ham  Nah I don't think he goes to usf, he lives aro...     0
5      spam  FreeMsg Hey there darling it's been 3 week's n...     1
6       ham  Even my brother is not like to speak with me. ...     0
7       ham  As per your request 'Melle Melle (Oru Minnamin...     0
8      spam  WINNER!! As a valued network customer you have...     1
9      spam  Had your mobile 11 months or more? U R entitle...     1
10      ham  I'm gonna be home soon and i don't want to tal...     0
11     spam  SIX chances to win CASH! From 100 to 20,000 po...     1
12     spam  URGENT! You have won a 1 week FREE membership ...     1
13      ham  I've been searching for the right words to tha...     0
14      ham                I HAVE A DATE ON SUNDAY WITH WILL!!     0
15     spam  XXXMobileMovieClub: To use your credit, click ...     1
16      ham                         Oh k...i'm watching here:)     0
17      ham  Eh u remember how 2 spell his name... Yes i di...     0
18      ham  Fine if that��s the way u feel. That��...     0
19     spam  England v Macedonia - dont miss the goals/team...     1

In [45]:
df.shape

(5572, 3)

### Splitting data into test and train part

In [116]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test =train_test_split(df.Message,df.spam,test_size= 0.2)

In [117]:
X_train.shape

(4457,)

In [118]:
X_test.shape

(1115,)

In [119]:
X_train

3989    (Bank of Granite issues Strong-Buy) EXPLOSIVE ...
1360    Yo dude guess who just got arrested the other day
25      Just forced myself to eat a slice. I'm really ...
2882                          Anything lor is she coming?
3733                    4 tacos + 1 rajas burrito, right?
                              ...                        
3326                  what number do u live at? Is it 11?
1740    UR GOING 2 BAHAMAS! CallFREEFONE 08081560665 a...
4059    This weeks SavaMob member offers are now acces...
1824                             Sent me ur email id soon
721                S'fine. Anytime. All the best with it.
Name: Message, Length: 4457, dtype: object

In [120]:
X_test

2910                     Sorry,in meeting I'll call later
3833           Watching tv lor. Nice one then i like lor.
4196    FREE for 1st week! No1 Nokia tone 4 ur mob eve...
4845    Pls help me tell Ashley that i cant find her n...
2731    Mm feeling sleepy. today itself i shall get th...
                              ...                        
4425                              Was it something u ate?
1503                      Ill be there on  &lt;#&gt;  ok.
761     We are at grandmas. Oh dear, u still ill? I fe...
4832    New Mobiles from 2004, MUST GO! Txt: NOKIA to ...
2753    Derp. Which is worse, a dude who always wants ...
Name: Message, Length: 1115, dtype: object

In [121]:
y_train

3989    1
1360    0
25      0
2882    0
3733    0
       ..
3326    0
1740    1
4059    1
1824    0
721     0
Name: spam, Length: 4457, dtype: int64

In [122]:
y_test

2910    0
3833    0
4196    1
4845    0
2731    0
       ..
4425    0
1503    0
761     0
4832    1
2753    0
Name: spam, Length: 1115, dtype: int64

In [123]:
type(X_train)

pandas.core.series.Series

In [124]:
X_train[:4]

3989    (Bank of Granite issues Strong-Buy) EXPLOSIVE ...
1360    Yo dude guess who just got arrested the other day
25      Just forced myself to eat a slice. I'm really ...
2882                          Anything lor is she coming?
Name: Message, dtype: object

In [125]:
type(y_train)

pandas.core.series.Series

In [126]:
y_train[:4]

3989    1
1360    0
25      0
2882    0
Name: spam, dtype: int64

In [127]:
type(X_train.values)

numpy.ndarray

### Vectorizing the words 

In [128]:
from sklearn.feature_extraction.text import CountVectorizer

In [129]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7811 sparse matrix of type '<class 'numpy.int64'>'
	with 59454 stored elements in Compressed Sparse Row format>

In [130]:
X_train_cv.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [131]:
X_train_cv.set_shape

<bound method spmatrix.set_shape of <4457x7811 sparse matrix of type '<class 'numpy.int64'>'
	with 59454 stored elements in Compressed Sparse Row format>>

In [132]:
v.get_feature_names_out().shape

(7811,)

In [133]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [134]:
v.vocabulary_

{'bank': 1209,
 'of': 4896,
 'granite': 3219,
 'issues': 3754,
 'strong': 6530,
 'buy': 1570,
 'explosive': 2715,
 'pick': 5207,
 'for': 2939,
 'our': 5013,
 'members': 4436,
 'up': 7186,
 'over': 5033,
 '300': 412,
 'nasdaq': 4700,
 'symbol': 6680,
 'cdgt': 1692,
 'that': 6819,
 'is': 3743,
 '00': 0,
 'per': 5152,
 'yo': 7708,
 'dude': 2476,
 'guess': 3262,
 'who': 7498,
 'just': 3869,
 'got': 3195,
 'arrested': 1055,
 'the': 6824,
 'other': 5007,
 'day': 2170,
 'forced': 2941,
 'myself': 4673,
 'to': 6942,
 'eat': 2511,
 'slice': 6223,
 'really': 5617,
 'not': 4826,
 'hungry': 3549,
 'tho': 6865,
 'this': 6859,
 'sucks': 6583,
 'mark': 4358,
 'getting': 3122,
 'worried': 7602,
 'he': 3362,
 'knows': 3958,
 'sick': 6146,
 'when': 7485,
 'turn': 7085,
 'down': 2424,
 'pizza': 5233,
 'lol': 4181,
 'anything': 980,
 'lor': 4202,
 'she': 6074,
 'coming': 1907,
 'tacos': 6691,
 'rajas': 5562,
 'burrito': 1558,
 'right': 5790,
 'network': 4751,
 'operator': 4967,
 'service': 6033,
 'free': 

In [135]:
v.get_feature_names_out()[6847]

'thgt'

In [136]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [137]:
np.where(X_train_np[2] != 0)

(array([2424, 2511, 2941, 3122, 3362, 3549, 3743, 3869, 3958, 4181, 4358,
        4673, 4826, 5233, 5617, 6146, 6223, 6583, 6859, 6865, 6942, 7085,
        7485, 7602], dtype=int64),)

In [139]:
X_train[:4]

3989    (Bank of Granite issues Strong-Buy) EXPLOSIVE ...
1360    Yo dude guess who just got arrested the other day
25      Just forced myself to eat a slice. I'm really ...
2882                          Anything lor is she coming?
Name: Message, dtype: object

In [140]:
X_train_np[2][2148]

0

In [141]:
v.get_feature_names_out()[3232]

'greatness'

In [142]:
from sklearn.naive_bayes import MultinomialNB

In [143]:
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [144]:
X_test_cv = v.fit_transform(X_test.values)

In [145]:
X_test_cv.toarray().shape

(1115, 3475)

In [146]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_train_cv)

print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3864
           1       0.99      0.97      0.98       593

    accuracy                           0.99      4457
   macro avg       0.99      0.98      0.99      4457
weighted avg       0.99      0.99      0.99      4457



In [114]:
X_test_cv = v.fit_transform(X_test.values)



y_pred = model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

ValueError: X has 3609 features, but MultinomialNB is expecting 7732 features as input.

### Doing same thing with pipeline 

In [148]:
from sklearn.pipeline import Pipeline

In [149]:
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [150]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [151]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       961
           1       0.97      0.94      0.95       154

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

